[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["cd backend && npm ci --legacy-peer-deps"]

[phases.build]
cmds = ["cd backend && npx prisma generate", "cd backend && npm run build"]

[start]
cmd = "cd backend && npx prisma migrate deploy && npm run start:prod"
